### ISSUE TITLE
dataset も分類 attribute も同一のオントロジーから作られているデータの問題

### ISSUE THREAD

**Issue by moriya-dbcls** [togodx/togodx-server#15]
https://docs.google.com/presentation/d/1dtp8BMyMbD6e2uD7viv0F6YRJVZzYG9J-hqvQUK_J8U/edit#slide=id.g13ea6b77307_0_0
attribute node と dataset となる leaf を個別に持つ形だと問題が出ないので、TogoDX-server 内部で修理するという方針だったが、昔過ぎて発注に入れ忘れてたのでメモ

**Comment by dsatoh** [comment]
nested_set_indexer内部でノードを複製する実装に変更したのでクローズします
